# Generated by Django 3.0.4 on 2020-09-23 14:30

from django.db import migrations, models

from ..models import Country

import csv


def extract_from_csv_and_save(apps, schema_editor):
    with open('suntime/migrations/countries.csv', 'r') as csv_file:
        reader = csv.reader(csv_file)
        for row in reader:
            country = {
                "lat": row[1],
                "long": row[2],
                "name": row[3]
            }
            Country.objects.create(**country)




class Migration(migrations.Migration):

    dependencies = [
        ('suntime', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(extract_from_csv_and_save),
    ]
